version: '3.3'

services:

  db:
    image: mysql:5.7
    environment:
      PMA_ARBITRARY: 1
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD: 123456
    command: mysqld --sql_mode=""
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3304:3306

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        PMA_ARBITRARY: 1
        MYSQL_USER: root
        MYSQL_PASSWORD:
        MYSQL_ROOT_PASSWORD: 123456
      ports:
        - 9004:80
      links:
        - db

  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'laravelapp'
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
