version: '3.3'

services:

  db:
    image: mysql:5.7
    environment:
      PMA_ARBITRARY: 1
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD: ${DOCKER_DATABASE_USER}
    command: mysqld --sql_mode=""
    volumes:
      - ./api/db:/var/lib/mysql
    ports:
      - ${DOCKER_MYSQL_PORT}:3306

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        PMA_ARBITRARY: 1
        MYSQL_USER: ${DOCKER_DATABASE_USER}
        MYSQL_PASSWORD:
        MYSQL_ROOT_PASSWORD: ${DOCKER_DATABASE_USER}
      ports:
        - ${DOCKER_PHPMYADMIN_PORT}:80
      links:
        - db

  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'laravelapp'
    ports:
      - ${DOCKER_APACHE_PORT_HTTP}:80
    volumes:
      - ./api:/var/www/html
